language: php

php:
  - '7.0'

env:
  global:
    - DATABASE_NAME=socialnet
    - DATABASE_URL=mysql://root@localhost/$DATABASE_NAME

services:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;"
  - mysql -u root --password="" $DATABASE_NAME < Test/socialnet.sql

script: phpunit ./Test/UserTest.php

dist: trusty